Created Czech locales
fosskers/aura pull request #744
Opened 2022-01-12 13:30 UTC by danalves24com

I created Czech translations for the locales. :czech_republic:

2022-01-12 16:07 UTC, ratijas requested changes
Hi, thanks for the patch! Please, fix all the suggested changes. You probably should also add yourself to the table at the end of [aura/doc/aura.8](https://github.com/fosskers/aura/blob/master/aura/doc/aura.8) man page.

2022-01-12 16:07 UTC, ratijas commented on aura/lib/Aura/Languages.hs
> +  Czech    -> "Nebyly nalezeny žádné balíčky"
Dot at the end?
```suggestion
  Czech    -> "Nebyly nalezeny žádné balíčky."
```

2022-01-12 16:07 UTC, ratijas commented on aura/lib/Aura/Languages.hs
> +    Czech      -> "Stav balíčku byl uložen"
Dot at the end?
```suggestion
    Czech      -> "Stav balíčku byl uložen."
```

2022-01-12 16:07 UTC, ratijas commented on aura/lib/Aura/Languages.hs
> +    Czech      -> "Zastaralý"
!!!
```suggestion
    Czech      -> "Zastaralý!"
```

2022-01-12 17:35 UTC, fosskers commented on aura/exec/Aura/Flags.hs
> +                , ( "arabic",     Arabic ),     ( "العربية",       Arabic )
That might be something to do with how characters display in his editor. They may have looked misaligned to him, so he "corrected" it as he saw it.

2022-01-12 17:43 UTC, ratijas commented on aura/exec/Aura/Flags.hs
> +                , ( "arabic",     Arabic ),     ( "العربية",       Arabic )
Let's not play the back-and-forth game between different editors then :)

2022-01-12 18:38 UTC, danalves24com commented on aura/lib/Aura/Languages.hs
> +  Czech     -> bt p <> "neexistuje"
If the word "balicek" would be there at the beginning, it would sound very odd.

2022-01-12 18:43 UTC, danalves24com commented on aura/lib/Aura/Languages.hs
> +    Czech     -> "Uvolněné" <> bytes <> "MB"
The way numbers work in czech can get complex, this would be the most optimal way of writing it.

2022-01-12 18:48 UTC, ratijas commented on aura/lib/Aura/Languages.hs
> +  Czech     -> bt p <> "neexistuje"
GitHub pro tip: you could scratch replies to all my comments in review mode, and submit them all at once instead of one by one :)

2022-01-12 19:07 UTC, danalves24com commented on aura/lib/Aura/Languages.hs
> +  Czech     -> bt p <> "neexistuje"
Thanks! Sorry - I am quite new to larger projects like these.

2022-01-12 19:23 UTC, ratijas commented on aura/exec/Aura/Flags.hs
> +                , ( "arabic",     Arabic ),     ( "العربية",       Arabic )
For me, Arabic looks wrong in Sublime Text now:

![Screenshot_20220112_222252](https://user-images.githubusercontent.com/6737986/149207758-78ac8e1c-b7e8-44b2-a059-f15fe4ca8779.png)

Romanian is fine, but I'd rather split it into separate commit.

2022-01-13 08:51 UTC, ratijas commented
@danalves24com unfortunately, your edits for aura.8 are wrong.  Watch carefully, and be mindful of tabs vs. spaces (hint: it matters).  You can preview the page with command `$ man -l path/to/aura.8`

2022-01-13 16:01 UTC, danalves24com commented
aura.8 should be all fixed now
![image](https://user-images.githubusercontent.com/60182044/149364123-65290f48-4144-449d-82cb-e86a7c006f2d.png)
![image](https://user-images.githubusercontent.com/60182044/149364247-91a53640-6292-4818-9533-21a110c65c35.png)

2022-01-13 16:03 UTC, danalves24com commented
Should I append Czech in all the various languages in Languages.hs? In reference to the test fail.

2022-01-13 18:23 UTC, ratijas commented
> aura.8 should be all fixed now

Good job!

> Should I append Czech in all the various languages in Languages.hs? In reference to the test fail.

Not sure I can answer that. Passing review onto @fosskers

2022-01-15 22:39 UTC, fosskers commented
Checking it over now.

2022-01-15 23:14 UTC, fosskers requested changes
Thank you for this! Please also add translations for the entries in `aura/aura/lib/Languages/Fields.hs` and then I can merge it. Keep in mind that I also just add two commits of my own to this PR, so you should pull the branch once before continuing.

2022-01-19 03:11 UTC, merged

2022-01-19 03:12 UTC, fosskers commented
Thank you very much for your hard work on this!